/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1"
	scheme "github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MPIsGetter has a method to return a MPIInterface.
// A group's client should implement this interface.
type MPIsGetter interface {
	MPIs(namespace string) MPIInterface
}

// MPIInterface has methods to work with MPI resources.
type MPIInterface interface {
	Create(*v1alpha1.MPI) (*v1alpha1.MPI, error)
	Update(*v1alpha1.MPI) (*v1alpha1.MPI, error)
	UpdateStatus(*v1alpha1.MPI) (*v1alpha1.MPI, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MPI, error)
	List(opts v1.ListOptions) (*v1alpha1.MPIList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MPI, err error)
	MPIExpansion
}

// mPIs implements MPIInterface
type mPIs struct {
	client rest.Interface
	ns     string
}

// newMPIs returns a MPIs
func newMPIs(c *SchedulingV1alpha1Client, namespace string) *mPIs {
	return &mPIs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mPI, and returns the corresponding mPI object, and an error if there is any.
func (c *mPIs) Get(name string, options v1.GetOptions) (result *v1alpha1.MPI, err error) {
	result = &v1alpha1.MPI{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mpis").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MPIs that match those selectors.
func (c *mPIs) List(opts v1.ListOptions) (result *v1alpha1.MPIList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MPIList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mpis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mPIs.
func (c *mPIs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mpis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a mPI and creates it.  Returns the server's representation of the mPI, and an error, if there is any.
func (c *mPIs) Create(mPI *v1alpha1.MPI) (result *v1alpha1.MPI, err error) {
	result = &v1alpha1.MPI{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mpis").
		Body(mPI).
		Do().
		Into(result)
	return
}

// Update takes the representation of a mPI and updates it. Returns the server's representation of the mPI, and an error, if there is any.
func (c *mPIs) Update(mPI *v1alpha1.MPI) (result *v1alpha1.MPI, err error) {
	result = &v1alpha1.MPI{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mpis").
		Name(mPI.Name).
		Body(mPI).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *mPIs) UpdateStatus(mPI *v1alpha1.MPI) (result *v1alpha1.MPI, err error) {
	result = &v1alpha1.MPI{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mpis").
		Name(mPI.Name).
		SubResource("status").
		Body(mPI).
		Do().
		Into(result)
	return
}

// Delete takes name of the mPI and deletes it. Returns an error if one occurs.
func (c *mPIs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mpis").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mPIs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mpis").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched mPI.
func (c *mPIs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MPI, err error) {
	result = &v1alpha1.MPI{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mpis").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
